In [4]:
import pandas as pd

df = pd.read_excel(r"C:\Users\DevaSri\Customer Churn Prediction\data\raw\customer_churn_1000_users.xlsx")
df.head()

,days_active,sessions_count,last_active_days,time_spent_learning,first_week_activity,completed_onboarding,tasks_attempted,tasks_completed,failure_rate,average_task_time,...,paywall_hits,paid_upgrade_done,dsa_sheet_access_attempts,avg_page_load_time,error_timeout_count,editor_video_crash_count,forced_relogin_count,login_failures,average_login_time,churn
0,32,50,15,369.47,22,1,82,36,0.72,53.28,...,10,0,15,2.39,5,9,15,8,2.94,0
1,46,58,30,89.71,39,0,122,49,0.06,59.48,...,1,1,3,5.04,4,1,4,9,12.33,1
2,27,93,0,482.52,15,0,24,87,0.99,36.64,...,19,1,13,5.11,15,2,10,3,4.91,0
3,0,82,2,260.41,21,1,119,89,0.95,63.23,...,9,0,5,5.68,7,7,9,5,9.98,0
4,24,41,4,316.12,18,0,59,94,0.45,38.15,...,25,1,4,4.96,4,6,19,1,7.48,0

In [5]:
# Shape of the dataset
df.shape

(1000, 22)

In [6]:
df.describe()

,days_active,sessions_count,last_active_days,time_spent_learning,first_week_activity,completed_onboarding,tasks_attempted,tasks_completed,failure_rate,average_task_time,...,paywall_hits,paid_upgrade_done,dsa_sheet_access_attempts,avg_page_load_time,error_timeout_count,editor_video_crash_count,forced_relogin_count,login_failures,average_login_time,churn
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,30.057000,60.364000,15.067000,254.900480,20.010000,0.508000,74.232000,58.192000,0.487990,46.204510,...,12.324000,0.495000,7.6330,3.347690,7.203000,5.008000,9.909000,5.100000,8.021720,0.334000
std,17.668444,35.096571,8.944748,136.572614,11.739409,0.500186,44.039251,35.784405,0.292351,25.567525,...,7.393354,0.500225,4.6383,1.606056,4.648376,3.178685,6.106882,3.212837,3.980607,0.471876
min,0.000000,1.000000,0.000000,30.360000,0.000000,0.000000,1.000000,0.000000,0.000000,2.190000,...,0.000000,0.000000,0.0000,0.500000,0.000000,0.000000,0.000000,0.000000,1.010000,0.000000
25%,14.000000,29.000000,7.000000,138.100000,10.000000,0.000000,36.000000,26.000000,0.230000,23.310000,...,6.000000,0.000000,4.0000,1.987500,3.000000,2.000000,4.000000,2.000000,4.640000,0.000000
50%,31.000000,60.000000,15.000000,245.870000,20.000000,1.000000,74.000000,55.000000,0.490000,46.360000,...,12.000000,0.000000,8.0000,3.360000,7.000000,5.000000,10.000000,5.000000,8.135000,0.000000
75%,45.000000,91.000000,23.000000,375.290000,30.000000,1.000000,112.000000,89.000000,0.750000,68.525000,...,19.000000,1.000000,12.0000,4.770000,11.000000,8.000000,15.000000,8.000000,11.440000,1.000000
max,60.000000,120.000000,30.000000,499.830000,40.000000,1.000000,150.000000,120.000000,1.000000,89.990000,...,25.000000,1.000000,15.0000,6.000000,15.000000,10.000000,20.000000,10.000000,14.960000,1.000000

In [8]:
df['churn'].value_counts(normalize=True)

churn
0    0.666
1    0.334
Name: proportion, dtype: float64

In [9]:
df.groupby('churn')[[
    'days_active',
    'sessions_count',
    'time_spent_learning'
]].mean()

       days_active  sessions_count  time_spent_learning
churn
0        30.648649       60.716216           258.966366
1        28.877246       59.661677           246.793054

In [10]:
df.groupby('churn')[[
    'tasks_attempted',
    'tasks_completed',
    'failure_rate',
    'average_task_time'
]].mean()

       tasks_attempted  tasks_completed  failure_rate  average_task_time
churn
0            74.360360        57.906907      0.490225          45.968468
1            73.976048        58.760479      0.483533          46.675180

In [11]:
df.groupby('churn')[[
    'paywall_hits',
    'solution_locked_hits',
    'dsa_sheet_access_attempts'
]].mean()

       paywall_hits  solution_locked_hits  dsa_sheet_access_attempts
churn
0         12.247748             15.385886                   7.690691
1         12.476048             15.356287                   7.517964

In [12]:
df.groupby('churn')[[
    'avg_page_load_time',
    'error_timeout_count',
    'editor_video_crash_count'
]].mean()

       avg_page_load_time  error_timeout_count  editor_video_crash_count
churn
0                3.296727             7.123123                  5.157658
1                3.449311             7.362275                  4.709581

In [13]:
df.groupby('churn')[[
    'forced_relogin_count',
    'login_failures',
    'average_login_time'
]].mean()

       forced_relogin_count  login_failures  average_login_time
churn
0                 10.060060        5.181682            8.178288
1                  9.607784        4.937126            7.709521

In [14]:
df.corr()['churn'].sort_values(ascending=False)

churn                        1.000000
last_active_days             0.820479
paid_upgrade_done            0.091897
completed_onboarding         0.056525
avg_page_load_time           0.044831
error_timeout_count          0.024277
paywall_hits                 0.014571
average_task_time            0.013043
tasks_completed              0.011256
solution_locked_hits        -0.001546
tasks_attempted             -0.004118
failure_rate                -0.010802
sessions_count              -0.014178
dsa_sheet_access_attempts   -0.017572
solution_view_attempts      -0.029077
forced_relogin_count        -0.034947
login_failures              -0.035918
time_spent_learning         -0.042060
days_active                 -0.047309
average_login_time          -0.055569
first_week_activity         -0.062042
editor_video_crash_count    -0.066517
Name: churn, dtype: float64

In [15]:
X = df.drop('churn', axis=1)
y = df['churn']

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [19]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred = model.predict(X_test_scaled)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[162   5]
 [  1  82]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       167
           1       0.94      0.99      0.96        83

    accuracy                           0.98       250
   macro avg       0.97      0.98      0.97       250
weighted avg       0.98      0.98      0.98       250

In [20]:
import pandas as pd

importance = pd.Series(model.coef_[0], index=X.columns)
importance.sort_values(ascending=False).head(10)

last_active_days        6.960534
avg_page_load_time      0.112420
tasks_completed         0.109746
solution_locked_hits    0.054183
tasks_attempted         0.049010
paywall_hits            0.031875
login_failures          0.031055
failure_rate            0.004654
days_active            -0.000448
paid_upgrade_done      -0.010801
dtype: float64

In [22]:
import joblib

joblib.dump(model, "../src/churn_model.pkl")
joblib.dump(scaler, "../src/scaler.pkl")

['../src/scaler.pkl']

In [23]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200,
                       random_state=42)

In [24]:
from sklearn.metrics import classification_report, confusion_matrix

rf_pred = rf_model.predict(X_test)

print("Confusion Matrix (Random Forest):")
print(confusion_matrix(y_test, rf_pred))

print("\nClassification Report (Random Forest):")
print(classification_report(y_test, rf_pred))

Confusion Matrix (Random Forest):
[[167   0]
 [  0  83]]

Classification Report (Random Forest):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       167
           1       1.00      1.00      1.00        83

    accuracy                           1.00       250
   macro avg       1.00      1.00      1.00       250
weighted avg       1.00      1.00      1.00       250

In [25]:
rf_importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

rf_importance.head(10)

last_active_days       0.747440
average_login_time     0.018599
time_spent_learning    0.017860
first_week_activity    0.017232
days_active            0.016862
tasks_completed        0.015632
avg_page_load_time     0.015391
tasks_attempted        0.015251
average_task_time      0.014749
paywall_hits           0.014690
dtype: float64

In [26]:
import joblib

joblib.dump(rf_model, "../src/churn_model.pkl")
joblib.dump(scaler, "../src/scaler.pkl")  # still keep scaler

['../src/scaler.pkl']